### ISSUE TITLE
[Device support] 

### ISSUE THREAD

**Issue by Oligarch** [Vaskivskyi/ha-asusrouter#109]
### The problem

Wrong model name: RT-AX58U_IPA

### Your device model

RT-AX82u

### Firmware type

Stock

### Firmware version

3.0.0.4.386_48664-g7ded0a1

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello, @Oligarch,

Thank you for your feedback! 👍🏻 

> Wrong model name: RT-AX58U_IPA

Does the integration recognise your RT-AX82U as RT-AX58U_IPA? Or do you mean, that you firstly accidentally put RT-AX82U, but wanted to put RT-AX58U?

Just because you have edited your issue, I am not sure now 🙂

**Comment by Oligarch** [comment]
Recognise my RT-AX82U as RT-AX58U_IPA. But everything works great

**Comment by Vaskivskyi** [comment]
I see. Seems like this is a common 'feature' of this model since I have one more report for the same matter. But that was on the Merlin firmware (so I thought, it was not a device bug, but firmware).

The model in the integration is taken from the NVRAM of the device directly. I will look into this and try to fix it in the next release.

Meanwhile, PR #110 will add RT-AX82U to the supported devices list and will close this issue.

Thanks! 👍🏻
