### ISSUE TITLE
[Device support] 

### ISSUE THREAD

**Issue by BeHappy2021** [Vaskivskyi/ha-asusrouter#114]
### The problem

Working fine - Did not test LED control though.

### Your device model

DSL-AC68U

### Firmware type

Stock

### Firmware version

3.0.0.4.386_47534-g23e7ef6

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello, @BeHappy2021,

Thanks for your feedback! 👍🏻 

I am glad, everything works for your device.

PR #115 will add it to the supported devices list and will close this issue.

In case you will experience any problems or you would like to submit a feature request, please open a new [issue](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose). This also goes if you will have problems with LED control (some devices do not support it due to firmware limitations). Unfortunately, I don't have any info about your model.

**Comment by BeHappy2021** [comment]
Thanks for this. I've actually used it to replace the official Asus integration as it works way better.
