### ISSUE TITLE
[Bug] asusrouter.light error

### ISSUE THREAD

**Issue by fookyuanloh** [Vaskivskyi/ha-asusrouter#144]
### The problem

Logger: homeassistant.setup
Source: setup.py:298
First occurred: June 15, 2022, 11:48:34 PM (1 occurrences)
Last logged: June 15, 2022, 11:48:34 PM

Unable to prepare setup for platform asusrouter.light: Platform not found (cannot import name 'ColorMode' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)).

Can we suppress this error?
Check model before running this config? 

### Your device model

RT-AC88U

### Firmware type

Merlin

### Firmware version

386.7_beta1

### Integration version with the issue

0.5.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2022.4.7

**Comment by Vaskivskyi** [comment]
Hello, @fookyuanloh,

Thanks for your feedback! 👍🏻 

This issue is not device-related, but HA backend related. Apparently, I have forgotten to rise up requirements for the HA version. The `ColorMode` enum which is failing to load in your case was added only on April 11, so probably got into release with 2022.5.0. I will check the HA source code and implement the needed changes to the integration requirements.

I am sorry for the inconvenience. Unfortunately, you would need to update your Home Assistant to a later version in order to use the integration.

**Comment by fookyuanloh** [comment]
Can't use 2022.5.0 and above
That messed up my onvif camera integrations where I don't get the cpu util for the cams

Hence I stayed on 2022.4.7 till date

**Comment by Vaskivskyi** [comment]
Sorry to hear that. Unfortunately yes, HA implements lots of breaking changes quite regularly trying to keep the release/month scheme 💥 

Unfortunately, there is no way for the integration to find out what is HA version and avoid loading not-yet-implemented parts. And I cannot just use deprecated values available up to 2022.4.7, since then everyone with 2022.5.0+ will get warnings in their log,

I am sorry, that I cannot help you. If you will later move to the newer HA versions, I will be glad to assist you with the integration.

Have a nice day!
