### ISSUE TITLE
[Device support] 

### ISSUE THREAD

**Issue by shivastefan** [Vaskivskyi/ha-asusrouter#149]
### Anything you want to mention?

i just cant do it :(

Logger: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:181
Integration: ASUS Router ([documentation](https://github.com/Vaskivskyi/ha-asusrouter), [issues](https://github.com/Vaskivskyi/ha-asusrouter/issues))
First occurred: 11:12:34 (2 occurrences)
Last logged: 12:52:41
Unknown error of type '<class 'asusrouter.error.AsusRouter404'>' during connection to 192.168.1.1: None

Logger: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:168
Integration: ASUS Router ([documentation](https://github.com/Vaskivskyi/ha-asusrouter), [issues](https://github.com/Vaskivskyi/ha-asusrouter/issues))
First occurred: 12:52:52 (2 occurrences)
Last logged: 12:52:55

    Connection refused by 192.168.1.1. Check SSL and port settings. Original exception: ("Cannot connect to host 192.168.1.1:8443 ssl:False [Connect call failed ('192.168.1.1', 8443)]", None)
    Connection refused by 192.168.1.1. Check SSL and port settings. Original exception: ("Cannot connect to host 192.168.1.1:8443 ssl:True [Connect call failed ('192.168.1.1', 8443)]", None

### Your device model

RT-N66U

### Firmware type

Merlin

### Firmware version

374.43_53D4j9527

### Does everything work well?

No

**Comment by Vaskivskyi** [comment]
Hello, @shivastefan,

Thanks for your feedback! 👍🏻 

I am sorry, integration does not work for you. As I see, you cannot even set up the integration. I can imagine, this is the last config flow table, you get to? [#2b. Complete device setup](https://github.com/Vaskivskyi/ha-asusrouter/blob/main/docs/setup.md#2b-complete-device-setup)

Is your router available via both HTTP and HTTPS connections? You can check this and the ports for connection in the device Web panel: `Administration - System - Local Access Config`.

1. If your device is only HTTP-available, please ensure that the `Use SSL connection` is unchecked. If you are using any other port than 80, please type it in the `Port` instead of `0`.
2. If only HTTPS, please check `Use SSL connection`. If the port is not the default 8443, you should provide it. If the port is correct, but you still get `connection refused`, please uncheck `Verify SSL certificate`.

Please, let me know if anything changed. Unfortunately, your device has old firmware, which I cannot currently test.

P.S. May I ask, why do you use Merlin 374.43 and not 380.70 which is the last stable release?

**Comment by shivastefan** [comment]
wow, thank you very much for your fast qualityanswer!
ty for your input!
i did set it to both again but i get the same errors, tried some combinations :(

well its a firmware from 16. may 2022, [https://onedrive.live.com/?authkey=%21ALJXk06IprzMMDc&id=9332FC159A7E129%216597&cid=09332FC159A7E129]

do i need to be in a domain or have some ddns? bc i cannot connect to router.asus.com for example!

**Comment by Vaskivskyi** [comment]
Hey, @shivastefan, sorry for the delay with the reply.

You can use the main or mirror download pages from [official Merlin webpage](https://www.asuswrt-merlin.net/download). Not the beta ones. E.g. https://sourceforge.net/projects/asuswrt-merlin/files/RT-N66U/Release/ has 380.70.0 release.

I was using the same release 380.70.0 on RT-AC66U (also an old device) and integration did work well. Maybe it is worth giving a try. Make sure to make some backups just in case

**Comment by Vaskivskyi** [comment]
Yes, I heard of it. There are different 3rd party firmware with more features.

I'm for now sticking with Merlin since it has all the stability of the stock firmware, as well as some nice features for VPN. Of course, it is not as customizable. On the better side, it has the full support of 802.11AX, which is a problem for 3rd-party firmware (or was a problem when I studied the question last time).
