### ISSUE TITLE
[Feature] Graphical Display of Traffic/CPU/RAM like the WebUI

### ISSUE THREAD

**Issue by LostOnTheLine** [Vaskivskyi/ha-asusrouter#188]
### The problem

I got this with the hope that I'd be able to have an actual display of the traffic usage & CPU/RAM like on the WebUI since the details say
> The integration uses the native Asus HTTP(S) API - the same way the web panel or mobile app works and relies on direct communications with your device.

But none of the available sensors seem to give me the data needed to do that.
Ideally a chart like this would be nice
![Asus AC68U Traffic](https://user-images.githubusercontent.com/60684934/185291475-5b2a3b82-418e-407e-a249-b65deaa18ba9.jpg)
But even having the data used for that could allow a similar card, though obviously not exactly the same design. I do something similar with the `Gauge Card` in _**Needle Gauge**_ mode to display current bloodsugar as reported by Dexcom. that would look different but be functional.

I would love to have a card like that for the `Bandwidth Monitor`, like in the Asus WebUI,
![Asus AC68U Bandwidth](https://user-images.githubusercontent.com/60684934/185291940-7db75c47-aa80-4cc8-b9d4-822d4f4c509f.jpg)
but again, that data doesn't seem to be available. I've tried with the sensors available but The RAM senor seems to give the right information, but CPU usage is updated so slowly that it is unusable, if for only 1 second during the ping it was using 20% but is otherwise at 80% it will just say 20%, which is of no practical use for monitoring. The RAM is fine because usage doesn't change drastically back & forth, but CPU does.
Now the bandwidth is a complete mystery because the only sensors seem to just tell what the maximum connection speed over the port/cable is. The sensors available just say 2100 & 1000 for the LAN & WAN speeds, not what's currently being used in the Upload & Download like you see on the router's page. If we're receiving the same data that the WebUI uses where is that information?
I understand having the polling interval set lower, & I'm sure there's some way to change how long those sensors wait between polling, but if it's using the same API as the Web I don't understand where all the other information is.

### Specific device(s)?

No

### Firmware type

Yes

**Comment by Vaskivskyi** [comment]
Hello, @LostOnTheLine,

Thank you for your feedback! 👍🏻 

First of all, the AsusRouter integration provides sensors (data of different sorts) and controls (switches), not the GUI for the cards. You can create cards in the frontend using default HA or custom cards installed from HACS.

About the sensors:

1. CPU. The `sensor.{device_name}_cpu` provides the CPU usage (in %) exactly the same way, as the Asus WebUI or module app. The way all 3 are working is calculating the usage as `(cpu_used_now - cpu_used_before)/(cpu_total_now - cpu_total_before)`. In this way, the resulting usage is always correct and is just an average over the time between `now` and `before`. If you are querying more regularly, you will average over a shorter time. This seems to be an advantage, but it is now - in reality each request of the data from the API hardly uses the CPU. As a result, your usage will raise because of this. If you try to check the usage each e.g. 1 second, the result will mostly be high because of the larger influence of your requests, not because of the actual usage. On a 10-second scale, 1 request is already small enough and on the 30-second scale, it is completely neglectable (that is why the default time to update sensors is 30 seconds). Exactly the same way this sensor provides `core_x` attributes with the usage per core of your device. You can plot it using any UI card as a gauge or a plot in time.
2. RAM. The `sensor.{device_name}_ram` provides RAM usage (in %) as in the Asus WebUI. It is calculated as `used / total`. and is correct for any point in time. If you would like to poll this data more regularly, you can change the time for polling sensors from the default 30 sec to any other value. This sensor has attributes `total`, `used` and `free`, that provide the values in KB as reported by the device API without any additional calculations. If you would like to show this data in the UI, you can either use the attributes directly or divide the values by `1024` to have the values in `MB` as shown in the WebUI.
3. Network sensors. The `sensor.{device_name}_{interface}_{type}` are providing network traffic for any `interface` selected during the integration setup (e.g. `WAN`, `LAN`, `WLAN0` (Wifi 2.4. GHz), `WLAN1` (5 GHz) and so on depending on the device) The `type` can be `download` / `upload` for the traffic on the interface or `download_speed` / `upload_speed` for the speeds. So if you want to find out how the speeds on the `WAN` interface, you need to plot (or show as a gauge) values of `sensor.{device_name}_wan_download_speed` and `sensor.{device_name}_wan_upload_speed`. If you didn't change these sensors' units, they would show the values in `Mb/s`. On the opposite, `sensor.{device_name}_{interface}_speed` for `lan` or `wan` as `interface` are showing the physical connection of the ports of the device. So, e.g. you can find out if the LAN port  number 3 is connected via cable (and is online, depending on the connected device) and which speed it provides (100 Mb/s, 1 Gb/s or 2.5 Gb/s etc) - this you can get from the attribute `lan_3` of the `sensor.{device_name}_lan_speed.

The integration provides lots of information via the available sensors. If you want to find out more about the sensors, please refer to the [sensors](https://github.com/Vaskivskyi/ha-asusrouter#sensors) section of the Readme - it has an as detailed description as possible.

If you want to change the polling time of the sensors, you can do it via the `Configure` button for the AsusRouter integration. Then you need to go to the `Time constants` tab of the configuration. Please, refer to the [setup and configuration manual](https://github.com/Vaskivskyi/ha-asusrouter/blob/main/docs/setup.md) for more details.

As I mentioned in the beginning, the integration provides only the sensors and switches. If you would like to show it in the same way in HA as in the Asus WebUI, you would need to use custom cards.

I hope, my answer will help you to set up your UI the way you want to.

**Comment by Vaskivskyi** [comment]
Since all the requested sensors and data are already in the integration, I am closing this issue.

Generation of a UI similar to Asus WebUI is not the purpose of this integration. For that, you should consider custom (or in-build) frontend dashboards.

If you will experiencing any problems with the integration, feel free to open [a new issue](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose). For suggestions and new ideas, please open [a new feature request](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose).
