### ISSUE TITLE
[Bug] Getting large number of similar messages in the log

### ISSUE THREAD

**Issue by RealGandy** [Vaskivskyi/ha-asusrouter#230]
### The problem

I am getting a significant number of these messages in the home assistant log file, for different endpoints

2022-10-05 08:27:09.578 WARNING (MainThread) [asusrouter.connection] Disconnected by the device while quering 'ajax_vpn_status.asp' with payload ''. Everything should recover by itself. If this warning appears regularly, you might need to decrease the number of simultaneous connections to your device.

While it gives me a solution, it doesn't tell me how to implement the solution (how do I decrease the number of simultaneous connections to your device.)

### Your device model

DSL-AC68U

### Firmware type

Merlin

### Firmware version

386.04-gnuton2

### Integration version with the issue

0.8.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.9.7 container

### Diagnostics information

[config_entry-asusrouter-07013c032cca67760c54e53728dbe99b.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/9714149/config_entry-asusrouter-07013c032cca67760c54e53728dbe99b.json.txt)

**Comment by Vaskivskyi** [comment]
Hello, @RealGandy,

Thank you for your feedback! 👍🏻 

Simultaneous connections can appear in 2 cases:

1. Inside the integration. If you have set the `interval to update entities` too low (e.g. 2 seconds only), some requests might still not be finished when new ones are made.
2. If you have the Asus app running on your mobile device in the background. Those can be updating data quite regularly. As a result, some of the requests from the integration are blocked.

In both cases, the reason is the fact, your device cannot reply to all the sent messages. This is too much device-dependant as well as FW-related. In order to minimize the number of warnings, you can increase the `interval to update entities` in the integration configurations. The recommended value is at least 10 seconds, but for some devices, it is better to have at least 30 seconds.

I will add more info to the warning (or better a link to the description here on GitHub).

**Comment by RealGandy** [comment]
Thanks for your prompt response. I’ll change the update interval and see how it goes
