### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by poudenes** [Vaskivskyi/ha-asusrouter#28]
Hi,

WONDERFUL integration!!! I love it!!! There are some other integration I also use because not all of them have all the information.
I have a list of (possible) features that maybe can be added in this integration. I think you have to ask the devs to add your integration as default then!!!

I use a **Asus GT-AX11000**

(grab from AsusWRT integration)
- CPU Temperature
- Load avg 1min
- Load avg 5min
- Load avg 15min

(grab from UPnP integration)
- Packets received total
- Packers send total
- Packets received packets/sec
- Packets send packets/sec
- WAN status: connected/disconnected
- External IP
- Bits received total
- Bits send total
- KiB received KiB/sec
- KiB Sebd KiB/sec

Would be so nice to have those settings also into your integration. Then I can remove the AsusWRT and UPnP one.

//KEEP UP THE GOOD WORK!

**Comment by Vaskivskyi** [comment]
Hey @poudenes ,

First of all, thanks for your feedback! 👍🏻 

There are more sensors planned for the integration soon (including external IP and WAN status binary sensor).

Out of your list:
 - bytes received/sent from UPnP is already in the integration as `{if}_download` / `{if}_upload` for any user selected interface `{if}` (e.g. `WAN`, `LAN` or others). The value of the sensors themself is in GB, but any of them has attribute `bytes` and can be accessed from e.g. templates using `{{ (state_attr('sensor.{device}_{if}_download', 'bytes')) }}`
 - the same for speeds received/sent. Sensors `{if}_download_speed` / `{if}_upload_speed` are in Mbits/s but have the raw attribute `bits/s`, from which you can calculate any of its derivatives, including KiB/s (`{KiB/s} = {b/s} / 1024 / 8`).

So I am not sure about adding more of the sensors without any new information. Adding these attributes was done exactly in order to provide any user with the possibility to calculate the needed value correctly.

Regarding the packet values usefulness, I am not convinced, sorry. But I am not in the field, so could be missing something. Could you please explain, how exactly this is useful information for monitoring?

In any case, this integration is still in development, so new features will be coming with time

**Comment by poudenes** [comment]
True, and agree. It's not urgent. It was just a list of options.. :) 

Hope you will add the rest haha!

**Comment by fookyuanloh** [comment]
Im using the following shell script to get the temp.

cat /proc/dmu/temperature = command to get cpu temp
wl -i eth1 phy_tempsense = radio 1 (2.4GHz) temp (divide by 2, then add 20)
wl -i eth2 phy_tempsense =  radio 2 (5.0GHz) temp (divide by 2, then add 20)

Would be great if this can be integrated into the next upcoming release

![image](https://user-images.githubusercontent.com/79247061/169008288-7dffb078-9d43-4d8c-9a0b-7962489fec3f.png)

Currently using the shell script + SNMP method to capture the temp
CPU & RAM using this plug-in

**Comment by peetereczek** [comment]
Hello,

I'm not sure whether it's valid, is CPU monitoring still in development, but sensors for RAM / CPU usage are unavaliable for my router RT-AX56U (with Merlin firmware)

![image](https://user-images.githubusercontent.com/42431204/169018123-850292c7-55f5-4000-8f8b-9cd771e1a71b.png)

**Comment by Vaskivskyi** [comment]
Hello, @fookyuanloh,

Thanks for your info :+1:

This is similar to what the aioasuswrt library is doing (the one behind the core asuswrt integration). Unfortunately, there is no possibility to run shell scripts when connecting to the device via API. I am checking if this data can be obtained any other way

**Comment by Vaskivskyi** [comment]
@poudenes,

Version 0.3.0 implements `wan_ip` sensor and `wan` binary sensor for status

**Comment by poudenes** [comment]
> @poudenes,
> 
> Version 0.3.0 implements `wan_ip` sensor and `wan` binary sensor for status

You informed me and 10 min later I got a notification on my watch that there is a HACS update :)

**Comment by Vaskivskyi** [comment]
Coming soon to AsusRouter (but highly depends on the device and firmware):

![image](https://user-images.githubusercontent.com/6554415/171903897-3a0d39f0-007f-4376-9392-00e584c25e20.png)
RT-AC66U (Merlin, v380.70)


![image](https://user-images.githubusercontent.com/6554415/171903991-02f8c083-c80f-499d-ae7c-b5b9163d17be.png)
RT-AX88U (stock, v386_48631)

**Comment by Vaskivskyi** [comment]
Hey, @poudenes,

Do you use stock AsusWRT firmware or Merlin on your device?

**Comment by poudenes** [comment]
I use the stock on my gt-ax11000

**Comment by Vaskivskyi** [comment]
> I use the stock on my gt-ax11000
> 
> Off topic is merlin better?

Just curious.

Merlin adds some new features. Not all of them are useful for everyone, so depends on your use cases. Also, as far as I know, AiMesh support is not as good as on stock.

With the next integration update, Merlin will get full support and some sensors, which are not yet available for the stock firmware.

![image](https://user-images.githubusercontent.com/6554415/172000097-9310ed13-ac3b-4c5b-91fa-ea7b54bf2bd4.png)

Also, mostly it has more temperature sensors (which I mentioned a couple of comments back). E.g. my RT-AX88U in stock has only CPU temperature, but Merlin gives also the temp of the WiFi modules. Not the most useful info, of course.

**Comment by Vaskivskyi** [comment]
Hi, @poudenes, @fookyuanloh,

With the freshly released [0.4.0](https://github.com/Vaskivskyi/ha-asusrouter/releases/tag/0.4.0), support for the temperature sensors is added. Maybe you can check it out?

Also, those with Merlin firmware will get access to the `load_average` sensors. Unfortunately, I haven't found a way to implement them on the stock firmware yet,

**Comment by poudenes** [comment]
I will update and let's see :)

The load average is also in AsusWRT integration and worked for the stock. Maybe you can check that integration how they did it.

**Comment by poudenes** [comment]
Temperature is working!

**Comment by Vaskivskyi** [comment]
> I will update and let's see :)
> 
> The load average is also in AsusWRT integration and worked for the stock. Maybe you can check that integration how they did it.

AsusWRT uses SSH or Telnet connection and can directly run any shell scripts. That could be a pro or a con, depending on the device. E.g. for some devices, it doesn't provide adequate traffic data. Or some sensors might be blank. The same is for the Merlin support and so on.

On the other hand, this integration is limited to what is provided by the HTTP API. This gives compatibility with almost any Asus device (because anything device-specific is already handled by the firmware). Also, quite all the bugs in the tracker were because of my mistakes in the code or no possibility to test some features, not because of the devices 🙂

**Comment by poudenes** [comment]
To keep the integration most compatible then stay at the api. It's not a big thing to have the load Average :) when there is no network then maybe the router is down haha :)

**Comment by Vaskivskyi** [comment]
Hey,

Since quite all of the requested features are already implemented (with some only for Merlin features and not being possible for the stock firmware), I would close this issue. It would be easier for me to monitor issues and feature requests, where I can implement something.

But in any case, all of the FW-specific features of the integration will be considered for future development even without issues in the tracker.

If you find any new useful feature to implement or bug in the integration, feel free to open a new [feature request or issue](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose)

**Comment by poudenes** [comment]
Good idea! Thanks for the great Addon!!! I consider to try merlin. But scare I screw up my perfect running network haha ;)

**Comment by Vaskivskyi** [comment]
> Good idea! Thanks for the great Addon!!! I consider to try merlin. But scare I screw up my perfect running network haha ;)

I would say, make a config backup and you should be safe enough. Lately, I am flashing my devices back and forth at least twice per week when testing the new release. WIthout any reset or readjustments

**Comment by poudenes** [comment]
This morning moved to Merlin. Everything in the house is working. Even old ESP devices... :) 
Now I have Load AVG also :)
