### ISSUE TITLE
[Feature] Reboot router

### ISSUE THREAD

**Issue by neuroverflow** [Vaskivskyi/ha-asusrouter#282]
### The problem

Thank you for your work, that integration is much better than the integrated one!

Do you think a switch to reboot the router is doable?
I have a mesh network than sometime requires to reboot the router to restore the connection between the nodes.

Thank you and good continuation!

**Comment by Vaskivskyi** [comment]
Hello, @neuroverflow,

Thanks for your feedback! :+1:

The integration has an in-built service to reboot the device - `asusrouter.service_reboot`. If you have only the main router connected to HA via the integration, it will be rebooted and integration will automatically reconnect.

Unfortunately, I have not tested this service yet in case of multiple devices setup in HA, since I have only one. So I cannot guarantee whether it works in such a case.

**Comment by neuroverflow** [comment]
Wow man! I re-checked the documentation and it's not there 😄 I tested and it's working, router and node rebooted! You rock!

**Comment by Vaskivskyi** [comment]
Apparently, it got lost at some point from the README.

Soon enough, there will be new and (hopefully) much better documentation for the integration 🙂

**Comment by sepodele** [comment]
Just a quick question from the sideline: Why did you add that feature as a service and not a button? I see more and more integrations use buttons but is there a guideline when to use which? Personally I prefer buttons since they show up in the integration and you don't have to guess if there are services available that you don't see. :)

**Comment by Vaskivskyi** [comment]
Hey, @sepodele,

No, I don't think there is any guide from HA on what to use. But I am already considering the possibility of a button instead of a service

**Comment by Vaskivskyi** [comment]
![image](https://user-images.githubusercontent.com/6554415/198391016-d50f2dd4-cb7f-413a-9b0e-85fdff309840.png)

Will be available with version 0.11.0
