### ISSUE TITLE
[Bug] Wrong Firmware Reported RT-AX58U

### ISSUE THREAD

**Issue by jazzyisj** [Vaskivskyi/ha-asusrouter#307]
### The problem

Integration is reporting firmware version 3004_386_45898-gfa90458 and is triggering update entity.
![image](https://user-images.githubusercontent.com/44064559/199075953-54b0c18b-2204-46b5-b2ab-7c4abbeccf0d.png)
Router reports firmware version 3.0.0.4.386_49674-ge182230 which is the version the update entity indicates is required.
![image](https://user-images.githubusercontent.com/44064559/199076221-060921d1-e01c-4a6c-8d92-35965875a735.png)
FWIW the Asus website indicates a much older firmware version as being the most current. 
![image](https://user-images.githubusercontent.com/44064559/199076667-f46cfbe9-b48a-471c-97f7-7ceccfa736a5.png)

### Your device model

RT-AX58U

### Firmware type

Stock

### Firmware version

3.0.0.4.386_49674-ge182230

### Integration version with the issue

0.11.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

v2022.11.0b4

### Is there anything useful in the logs?

```txt
N/A
```

### Diagnostics information

[config_entry-asusrouter-d7f26af8a2f7da0d8ec212eca5a59111.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/9903715/config_entry-asusrouter-d7f26af8a2f7da0d8ec212eca5a59111.json.txt)

**Comment by ejpenney** [comment]
Not sure if this is the same issue or not, with RT-AC66R (Merlin) I see this:

![image](https://user-images.githubusercontent.com/21226768/199084156-96ccef60-35d0-4b71-8f03-1e60a9b6415f.png)

The ASUS Router Android app reports the suggested version: 3.0.0.4.380.70_0

![image](https://user-images.githubusercontent.com/21226768/199085091-f771ef7b-d6e8-4f08-b47a-3e97792b6e6b.png)

I can file a separate ticket if this is not related.

**Comment by Vaskivskyi** [comment]
Hey, @jazzyisj,

Sorry for this bug. It will be fixed soon.

Btw, the latest is the version you have, as per the Asus web page

![image](https://user-images.githubusercontent.com/6554415/199181555-d690d926-eeb1-4b2e-aed1-396af4aa19f4.png)

---

@ejpenney,

It's fine to be in this issue. Looks like old Merlins like to report firmware versions differently... This will also be fixed soon.

**Comment by jazzyisj** [comment]
Ha, I was looking at the firmware page for RT-AC58U, not RT-AX58U.  Thanks for looking into it!

**Comment by Vaskivskyi** [comment]
@jazzyisj,

Please, check with the new version 0.11.1 whether the `update` entity is fixed.

@ejpenney,

Please, also check the 0.11.1 version. I am not sure if that will help in your case, but it does worth checking.

**Comment by ejpenney** [comment]
The message is different now:

![Screenshot_20221101-081430.png](https://user-images.githubusercontent.com/21226768/199268208-0eed11fb-465d-4215-9595-02dd148ee214.png)

**Comment by Vaskivskyi** [comment]
> The message is different now:
> 

Can you please login into the Web UI of your device? Then change the address of the page from `https://device_ip/index.asp` to `https://device_ip/detect_firmware.asp` manually. Copy the text and send it here.

It should be similar to:

```
webs_state_update = '1';
webs_state_error = '0';
webs_state_info = '386_8_0';
webs_state_info_beta = '';
webs_state_REQinfo = '';
webs_state_flag = '0';
webs_state_upgrade = '';
webs_state_level = '0';
sig_state_flag = '0';
sig_state_update = '1';
sig_state_upgrade = '1';
sig_state_error = '0';
sig_ver = '2.320';
if(cfg_sync_support){ cfg_check = '9'; cfg_upgrade = ''; } if(pipefw_support || urlfw_support){ hndwr_status = '99'; }
```

Unfortunately, your device is reporting the FW version in some strange form, not like other devices. Let's see, whether we can use it somehow properly

**Comment by gmariotti** [comment]
Interesting enough, the firmware version for Merlin now doesn't look fully correct 😅 in 0.11.0, the version reported was `386_7_2`, while in 0.11.2 is `3.0.0.4.386.7_2`. The last part, `386.7_2`, is the correct one displayed in the UI, but where does that `3.0.0.4` come from?

**Comment by ejpenney** [comment]
I logged in to my router, changed the URL as specified and I get this page:

![image](https://user-images.githubusercontent.com/21226768/199281133-8657a260-2926-46e9-9021-0c7a15af4dc5.png)

Not much more helpful in the page source:

![image](https://user-images.githubusercontent.com/21226768/199280817-8a9cad4c-aedb-4830-a269-5fa2f2b69ff1.png)

I wonder if this might be because I have the device in AP mode?  The Web UI in AP mode is severely limited.  If there's another way to get the version data I'm willing to try.  Otherwise as my next step I was going to change the mode back to router, see if the issue goes away... If it doesn't maybe detect_firmware.asp will at least work better.  With this particular device it also would not hurt for me to factory reset and re-install the firmware.

If there's anything else you'd like me to try I'll do it.  Otherwise I'll report back when I've done all this...

**Comment by Vaskivskyi** [comment]
Hey, @gmariotti,

Merlin likes to hide the first part of the FW version in the interface, even though for Asus this is the `major` of the version. It was always reported in the device info as full.

![image](https://user-images.githubusercontent.com/6554415/199281428-7f111365-b021-4ad5-aaf7-ffaa3d1d01ca.png)

The update entity first did not have it, since some of the newer FW versions are just reporting `minor` and `build` parts of the version, but in order to process the update status properly, versions are now used as the whole, not just some parts. Because again different devices are just creating a mess.

P.S. For Asus `3.0.0.4` major is important because it is used to specify beta releases - then the version is `9.0.0.4`. On the opposite, Merlin is just adding `-beta` in the end, so there is no real need in `3.0.0.4`.

---

@ejpenney,

No need to change anything with your device. I have already found a similar `RT-AC66U` which has exactly the same issue with `update` entity. So I can do some troubleshooting on that device. I will let you know when I'll find the fix.

**Comment by Vaskivskyi** [comment]
Hey, @ejpenney,

Please, check the new version 0.11.3, which is already available via HACS. It should solve your problem with the `update` entity

**Comment by ejpenney** [comment]
Looks good to me!

![image](https://user-images.githubusercontent.com/21226768/200053269-f895cec9-e1e5-4740-b9f4-60ffa425e7fd.png)

**Comment by Vaskivskyi** [comment]
Great. Since all the issues in here, I will close it. In case you will experience any other problems, please open a new issue. 🍻
