### ISSUE TITLE
[Feature] Meaningness of Restart HTTP Daemon

### ISSUE THREAD

**Issue by scetu** [Vaskivskyi/ha-asusrouter#344]
### The problem

Hello @Vaskivskyi, 

once again, thank you for this great integration.
Today I had an issue when my router RT-AX58U has not been responding to HTTP request (I was unable to load WebUI) and integration has started failing, cause as I understood it is using HTTP as main connection source, however router has been otherwise functional (internet, and other services has been working). This started me thinking about meaning of integration button Restart HTTP daemon when HTTP is not available or is dead on router side. What I have been thinking if this button would not be better to have over ie. SSH cause then it maybe makes more sense in cases like mine. What do you think, would it be possible to re-route this button to run ssh, login to router and run `service restart_httpd`?

### Specific device(s)?

No

### Firmware type

No

**Comment by Vaskivskyi** [comment]
Hello, @scetu,

The `button.{device}_restart_http_daemon` can restart the daemon which is partially stuck - this happens with some devices and some firmware after several days of active usage. It can be seen from the integration - some sensors stop updating (e.g. `lan_speed`, `wan_speed`) and from the Web UI - this tab is not updating anymore

<details>
<summary>Snapshot</summary>

![image](https://user-images.githubusercontent.com/6554415/202843042-e23514be-a4a8-45e7-a46b-110f2b1d5bde.png)
</details>

The reason is, that some of the API endpoints are crashing and cannot be accessed anymore. The button allows restarting only this part of the router, which solves the problem. Of course, the router by itself can be rebooted - but that would require at least a minute and all the devices to reconnect.

Obviously, since AsusRouter is using HTTP API, if the router is not responsive anymore, it cannot be rebooted as well.

The reason, why AsusRouter has so many features in comparison with the HA in-built AsusWRT - is exactly the usage of the HTTP API. SSH is not supported, since that would require rebuilding half of the integration. And there are no plans to support it yet.

---

You can create automation (or script) to SSH from HA directly to the router and reboot it, using the `command_line` HA platform.
