### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#357]
### The problem

on new beta core integration stop working
logs clear
![image](https://user-images.githubusercontent.com/42905545/205188444-6ad4fe67-1719-4b01-b372-14a9ffa62d29.png)

### Your device model

*************

### Firmware type

Stock

### Firmware version

*****************

### Integration version with the issue

*********************

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.12.0b1

**Comment by thewazz1** [comment]
I have the same issue, it looks like HA core went to different version of asusrouter, below is the error message that I have. 

Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 7:00:08 PM (3 occurrences) 
Last logged: 7:00:15 PM

Unable to install package asusrouter==0.12.0: ERROR: Cannot install asusrouter==0.12.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by Vaskivskyi** [comment]
@milandzuris,
@thewazz1,

Thanks for your reports! This issue will be fixed as soon as possible.

**Comment by milandzuris** [comment]
> @milandzuris,
> @thewazz1,
> 
> Thanks for your reports! This issue will be fixed as soon as possible.

Please add this fix to beta

**Comment by Vaskivskyi** [comment]
Version 0.13.1 of the integration is already available in HACS. Please, check it out - it should work with HA 2022-12

**Comment by milandzuris** [comment]
> 

it works
