### ISSUE TITLE
[Test with your device] AiMesh support

### ISSUE THREAD

**Issue by Vaskivskyi** [Vaskivskyi/ha-asusrouter#40]
Apparently, AiMesh connected devices (when at least 2 are used together) have some peculiarities in the reported data (e.g. reported traffic #30 and number of connected devices, so device_trackers, https://github.com/Vaskivskyi/ha-asusrouter/issues/16#issuecomment-1121311921).

Unfortunately, I have only one device supporting AiMesh, so no tests can be held by me until I get another one.

Looking for people with a will to help test this. What would be needed from you:
- Usage of `Developer tools` in your browser to monitor what data is fetched from the router by the web panel.
- Test new python library ([Vaskivskyi/asusrouter](https://github.com/Vaskivskyi/asusrouter)) builds.

If you would like to help, just comment here with the device model and firmware version.

**Comment by robertoleonardo** [comment]
I'm happy to help -- i have two AX (XT8) routers (firmware:  3.0.0.4.386_48706-g5f8f479) BUT the integration doesn't seem to be working in the first place.  If i enter the correct information, it takes me past the config page but then i get a "failed to set up"  error on the integration landing page.  once that is sorted out -- happy to help.

**Comment by Vaskivskyi** [comment]
Hi, @robertoleonardo. Could you please open a new issue and post errors/warnings from the HA log for the integration. If integration has shown "failed to set up", there should be something from `custom_components.asusrouter`.

Let's solve it and then can try testing AiMesh 🙂

**Comment by robertoleonardo** [comment]
@Vaskivskyi figured it out! i had been unchecking 'enable device monitoring' because i didn't want 100 new devices added -- that was making it throw the error.  i've got the integration up and running now.  i've got to do some work today but just let me know how i can help with testing and i'll tinker in the next couple of days.

**Comment by Vaskivskyi** [comment]
Great!

1. The first part would be observation. I would need to know first if:
a. you have WAN traffic and speed sensors available and working
b. the `Connected Devices` sensor shows the same number of users as the Asus web panel. This could change with time. Apparently, the sensor in the integration can show more than the web panel. I am curious if this difference is changing over time

**Comment by robertoleonardo** [comment]
looks like both things are working! 47 connected devices is right. though, not sure what that small download number is for wan2 - i don't have dual wan set up
![50E283B9-62D0-4267-BF80-9B79B180D2AA](https://user-images.githubusercontent.com/13153043/168494044-11300cd6-4979-47cc-852e-36587ae5d6d9.png)

**Comment by Vaskivskyi** [comment]
WLANs are different WiFi network interfaces. `0` stands for 2.4 GHz WiFi, `1` and `2` for different 5 GHz WiFi interfaces. Probably, most of your devices are connected to `1`, that is why `2` is not too active.

What I am looking for is the `WAN` interface, which would be traffic with the outer world (so, e.g. your internet provider). You can check if it is at all visible by clicking the `Configure` button of the integration.

![Untitled-1](https://user-images.githubusercontent.com/6554415/168495503-74950940-070a-4929-8068-154d90c4dc15.png)

There will be the same list of available interfaces like the one shown when the integration was first set up.

![Screenshot 2022-05-15 235248](https://user-images.githubusercontent.com/6554415/168495398-a047b402-56c9-4cc5-9b1c-390eb6b7a12e.png)

**Comment by robertoleonardo** [comment]
ya sorry i'm dumb i realized that after i posted. here you go. that wan download number might be right even though it's low - i just reinstalled the integration an hour or two ago when i was tinkering. 
![05215EE4-5CE3-433E-8258-F5091B72C0D5](https://user-images.githubusercontent.com/13153043/168497847-f4f772ff-9688-464c-9fe1-36da1e389ba4.png)

**Comment by Vaskivskyi** [comment]
> 47 connected devices is right

I suppose, when you saw those 47, the web panel was showing it the same way? What does the `AiMesh Node` value in the web panel show to you? Is it 1?

![Screenshot 2022-05-16 230046](https://user-images.githubusercontent.com/6554415/168682059-c0b141b1-16c5-41ec-a91c-a20b6e39c3e7.png)

Also, the traffic values reported in sensors `{}_download` and `{}_upload` do not depend on the integration. Only on the router itself. They reset to 0 either if the router is rebooted or if the value overflows some maximum (which is different for different models). So even if you remove the integration and set it up again, they should stay the same

**Comment by robertoleonardo** [comment]
oh, i didnt realize you were looking for exact exact. i believe when i saw 47 in the integration the asus app told me 48. in my book, a difference of 1 is still accurate. the asus app / web interface are so slow and buggy i assume there's just some slight delay in reporting. because when it says i have 48 devices, inevitably it'll drop down a few or go up a few just from devices going to sleep and such.

so yea - 47 wasn't exact exact. but it was as close as i could reasonably hope for.

as for ai mesh node -- i didn't look yesterday. right now it says 38+6. sometimes it randomly splits devices pretty close to 50/50. other times it has a single device on the node and the rest on the
main router.

though, interesting. i did now just compare the hass sensor to my total number and the allocation between the two asus devices - my TOTAL says 46, which is 2 higher than the sum of the 38+6 (i guess the routers themselves are included in the total but not the node specific counts)

and while i am getting 44 (sum of two nodes) and 46 in asus, the hass sensor is giving me 45. which is consistent with what i saw the other day - was getting 47 in hass and 48 total in asus. so maybe it's always 1 less than the total in asus and 1 more than the sun of the devices connected to nodes? perhaps the hass sensor is not counting the main router. but is counting the node (which actually makes a lot of sense)?

--
rob lee
m: 310.431.1619

**Comment by Vaskivskyi** [comment]
Ok, I see 👍🏻 

I'll prepare some code for more tests to collect data directly from the device. It could take a couple of days

**Comment by bladecoates** [comment]
I have two RT-AX92U that are using mesh. They appear to be working. I'm happy to test anything. The"ASUSWRT" and UPNP integrations leave a lot to be desired. 

I'm currently working on setting up a dashboard for it.

**Comment by bladecoates** [comment]
![D1BF0E3C-03E7-47A8-9354-FAEAFB0A629C](https://user-images.githubusercontent.com/4097682/169916954-cbe01823-81d9-4a9c-8c03-a01e72e914b0.png)

Integration is showing 57 devices. I have ever entity enabled except for the device_trackers. 

Just @ me if there is anything specific you want tested.
