### ISSUE TITLE
[Bug] Integration not loading after update to 0.19.0

### ISSUE THREAD

**Issue by FerLSanchez** [Vaskivskyi/ha-asusrouter#526]
### The problem

After updating to 0.19.0, the integration is not loading, with this in the log (added in the details box)

My enviroment is an aimesh setup, with a TUF-AX5400 as main, another one as node, and a RT-AC57U V3 as another node.
Working without any problem until the update :/

Firmware 3.0.0.4.386_50224-gc45ea49 (downgraded from 388 which is a complete MESS with aiMesh...)

### Your device model

TUF-AX5400

### Firmware type

Stock

### Firmware version

3.0.0.4.386_50224-gc45ea49

### Integration version with the issue

0.19.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.2.2

### Is there anything useful in the logs?

```txt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 311, in async_identify
    data = item.method(raw[item.value]) if item.method else raw[item.value]
KeyError: 'serial_no'
```

**Comment by Vaskivskyi** [comment]
Hey,

Sorry to hear you are experiencing problems with AsusRouter

The error message says that the serial number of the device was not properly fetched from the device NVRAM. It is required in order to create a unique_id for the device in HA. When downgrading from 388 to 386 build, did you reset your device or just installed 386 on top of 388?

Could you please also try restarting the device with the error and trying to reload the integration (or restart HA) afterwards? I know, that might be obvious, but actually, there are quite several bugs with the Asus API, that are resolved with a simple restart (or reboot of the whole AiMesh if in mesh mode)

**Comment by FerLSanchez** [comment]
Thanks for the support. The downgrade was made weeks ago (in fact I'm downgraded now the component to 0.18.4 and it's working again), and it was with a full reset.

Is there any way of knowing with of the three routers is causing the problem? Restarting HA didn't work (but has worked after downgrading the integration...).

Thanks again

**Comment by Vaskivskyi** [comment]
If all 3 devices are set up in the HA, the one that gets into the error with `KeyError: 'serial_no'` in the log should probably become unavailable (all of its sensors and other entities will be greyed out and have `unavailable` state)

**Comment by FerLSanchez** [comment]
Ok, after downgrading and upgrading again the integration, and rebooting home-assistant a couple of times, now magically works. Unexplainable but, as you were saying, it seems to be a not-so-reliable API.

Thank you for the support and the amazing work.

**Comment by Vaskivskyi** [comment]
👍🏻 Great that it works now. In case you will be experiencing any other problems, please open a new issue
