### ISSUE TITLE
device_tracker entities not removed

### ISSUE THREAD

**Issue by Morriz** [Vaskivskyi/ha-asusrouter#575]
### The problem

Hi, I disabled device tracking functionality and expect to see the entities removed from hass. (They show up as disabled only.) I restarted hass but no dice.

### Your device model

RT-68U

### Firmware type

Stock

### Firmware version

3.0.0.4.386.49703_gc2cdfc8

### Integration version with the issue

pleawse remove as you already request diagnostics

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.3.1

### Diagnostics information

[config_entry-asusrouter-6f1a6f387af8a79c370fc0e353f1aed4.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10919965/config_entry-asusrouter-6f1a6f387af8a79c370fc0e353f1aed4.json.txt)

**Comment by Morriz** [comment]
I think this is the default HASS behaviour: entities are kept until the integration is removed. Closing this for now as I was able to remove the entities from `.storage/core.entity_registry`

**Comment by Vaskivskyi** [comment]
Hello,

Yes, this is standard HA behaviour. In principle, the integration can remove its own entities if needed, but in general, that would not be the best tactics

P.S. Integration version is asked in the template, because for some users integration breaks without the possibility to download diagnostics altogether. Even if it works, amount of issues with attached diagnostics is not more than 20%
