### ISSUE TITLE
[Device support] RT-AX88U

### ISSUE THREAD

**Issue by lassjoh** [Vaskivskyi/ha-asusrouter#617]
### Anything you want to mention?

Hi
I'm using Asusrouter for parental control, but I can't control internet access for laptops and desktops. I've used the mac address to find the entities for IPADS, playstation etc, but I can't find the entities for the computers. What can I do?

### Your device model

RT-AX88U

### Firmware type

Merlin

### Firmware version

3004.388.4

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the late reply. It can be that some of the device tracker entities (in your case ones for the laptops and desktops) are automatically disabled by Home Assistant. Can you please check them? In case they are actually disabled, please enable them and try to set a parental control rule. Let me know whether it helps or not, so that we can solve the problem you are experiencing

**Comment by lassjoh** [comment]
Hi!

Thank you for answering my question. I removed the integration and
installed it again and now it suddenly works :)
Sometimes when i reboot my HA i says it has found my router and want to add
it although its already integrated.
I had 2 instances with the same router. Maybe that was the problem.

Lasse

lør. 28. okt. 2023 kl. 14:33 skrev Yevhenii Vaskivskyi <
***@***.***>:

**Comment by Vaskivskyi** [comment]
Good, that your issue is solved :+1:

Yes, there is an issue with auto-discovery giving false-positives even when the device is already set up. I am still working on it - that's something happening only for a part of users which makes it quite hard to troubleshoot. But it will be eventually fixed
