### ISSUE TITLE
[Bug] GT-AXE16000 / Device crash

### ISSUE THREAD

**Issue by Vendivar** [Vaskivskyi/ha-asusrouter#628]
### The problem

HA Integration crashes router and makes it restart frequently 

### Your device model

GT-AXE16000

### Firmware type

Merlin

### Firmware version

3004.388.4_0

### Integration version with the issue

latest

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Supervisor 2023.10.1

**Comment by Vaskivskyi** [comment]
Hello,

I am sorry to hear you are experiencing issues with the integration. Can you please provide some more details on the way you are setting up the integration, so that I can help solve this:

- What are the settings you are choosing when setting up the integration?
- Is there anything in the Home Assistant log (error or warning messages) from AsusRouter?
- Does the integration get any data from the device? Does it update sensors and other entities in HA before your device crashes?

**Comment by Vendivar** [comment]
What are the settings you are choosing when setting up the integration?
I have tried both port 0, and a custom 8845 for SSL (changed 8445 on router also) 

Device Mode: Router
Enable device control: Both enabled and disabled
Enable per-sensor update intervals: Disabled
Enable device trackers Both enabled and disabled
Interfaces to monitor: All except USB (Not using USB)
Home Assistant Events: All checked

Is there anything in the Home Assistant log (error or warning messages) from AsusRouter?
I was not able to discern any error logs from the router (when it hard crashes like this I cant find anything in the logs around the time it crashes)
Since the router crashes I also lose connectivity to HomeAssistant but I am not seeing anything in its logs either. 

Does the integration get any data from the device? Does it update sensors and other entities in HA before your device crashes?

The integration gets all relevant sensors updated.

**Comment by Vendivar** [comment]
The only other thing I see in HA logs that doesn't seem relevant to the actual router crashing is: `2023-10-28 12:29:31.464 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.gt_axe16000_connected_devices exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
`

**Comment by Vendivar** [comment]
When I tried it again just now I got these errors from HA around the time of the crash

`2023-10-28 12:41:40.649 ERROR (MainThread) [aioasuswrt.connection] Host timeout.
2023-10-28 12:42:09.831 ERROR (MainThread) [homeassistant.components.asuswrt.router] Error connecting to ASUS router 192.168.1.1 for device update: [Errno 113] Connect call failed ('192.168.1.1', 22)`

**Comment by Vendivar** [comment]
Got a crash log this time

[full crashlog.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/13196528/full.crashlog.txt)

**Comment by Vaskivskyi** [comment]
Thanks for the log. I will check it out.

From the HA error message, it looks like either you have too many devices connected to your router, that they don't fit into a sensor, or actually, something is wrong with the communication with your device - that would explain crashes of the device.

Please, allow me some time.

**Comment by Vendivar** [comment]
Is there a way to exclude state attributes to not show every sensor connected to that entity?

**Comment by Vendivar** [comment]
~180 devices

**Comment by Vendivar** [comment]
180+ devices

**Comment by Vaskivskyi** [comment]
This is something which I won't be able to test, unfortunately. Easy test for you will be - log in to the Web UI of your router and open the list of all the connected devices (the one dynamically refreshing - behind the `View List` button on the image above). After 5 min it will be obvious whether there is an issue because of the device number. Asus likes to eat all the RAM fastly and easily. 

You might also want to watch the dynamic data loaded in the Dev tools of you browser (`Dev tools - Network - XHR`) - there shouldn't be any failed resources

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/705c198b-97be-42ba-becd-00b361a1ca3c)

When we find this out, we'll be able to understand whether it is AsusRouter causing crashes or just the API itself

**Comment by Vaskivskyi** [comment]
Version `0.28.0` of the integration will help solve the issue on the HA side with too long of the attribute for the `connected_devices` sensor. This attribute can be now disabled in the integration settings.

Unfortunately, to help with the issue on the device side, I would need your help

**Comment by Vaskivskyi** [comment]
If you still want to proceed with the issue debugging and fixing, please, reopen this issue. If not, unfortunately, I cannot do anything without help from your side - my device count is below 30 and I don't have any possibility of getting 100+ more on the network
