### ISSUE TITLE
[Bug] Wrong firmware version detected for AiMesh Node after update to 0.23.x

### ISSUE THREAD

**Issue by thewan056** [Vaskivskyi/ha-asusrouter#684]
### The problem

I have an RT-AX5400 AiMesh Node added as an additional device using your AsusRouter integration. Before the update to 0.23.x it was showing the correct firmware version. After the update it is now showing the firmware version of my main router. 

The device info section is showing the correct firmware version:
<img width="296" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/24851051/9adb632b-bed9-4224-9ae5-a90e8d690649">

But the firmware update is wrong, before this new update it was showing the correct firmware, the same one as the device info:
<img width="533" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/24851051/f5cf4d38-1ac0-4553-9776-625faaeea12d">

Since the AX5400 uses a fork of merlin by gnuton because it is not supported by merlin officially, updates for it are released later and therefore I would like the previous ability to have separate tracking of each device firmware if possible.

### Your device model

RT-AX5400

### Firmware type

Merlin

### Firmware version

3.0.0.4.388.4_0-gnuton1_tuf

### Integration version with the issue

since 0.23.0, updated to 0.23.6

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.11.1

### Additional information

If it helps my main router is the RT-AX86U running 3.0.0.4.388.4_0 Merlin FW.

**Comment by Vaskivskyi** [comment]
Hello. Sorry to hear you are experiencing issues with the latest versions.

Let me check this. I will let you know if I need any more info from your side

**Comment by Vaskivskyi** [comment]
Do you mind running a small Python script? You need to run it from any Python 3.11+ environment with `asusrouter` installed. You can install it using `pip3 install asusrouter==1.0.5`. When ready, create some `test.py` file with the following content (don't forget to replace `_host`, `_username` and `_password` with your values.

```python
"""Small test for available data from your AsusRouter"""

import asyncio

from asusrouter import AsusRouter
from asusrouter.modules.data import AsusData


async def gather_data(host, username, password, use_ssl):
    """Method to gether the known data"""

    # Initialize
    router = AsusRouter(
        hostname=host, username=username, password=password, use_ssl=use_ssl
    )

    # Connect
    await router.async_connect()

    # Get the client list
    clients = await router.async_get_data(AsusData.FIRMWARE)
    print(clients)

    # Disconnect
    await router.async_disconnect()


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_use_ssl = True

loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))

loop.close()
```

It should output something like this in your console:

`{'webs_state_error': '0', 'webs_state_info': '3004_388_24198-g380c137', 'webs_state_info_beta': '', 'webs_state_REQinfo': '3004_384_6210-g8fa97e7', 'webs_state_flag': '0', 'webs_state_upgrade': '', 'webs_state_level': '0', 'sig_state_flag': '0', 'sig_state_update': '1', 'sig_state_upgrade': '1', 'sig_state_error': '0', 'sig_ver': '2.376', 'cfg_check': '9', 'cfg_upgrade': '', 'hndwr_status': '99', 'state': False, 'current': '3.0.0.4.388.24198_g380c137', 'available': '3.0.0.4.388.24198_g380c137'}`

Please, post this output here, so that I'll know whether there is an issue in the backend library or in the integration itself

**Comment by Vaskivskyi** [comment]
@thewan056, Please, check version `0.23.7`and let me know whether the issue persists

**Comment by Vaskivskyi** [comment]
In case if the issue was not solved, please, reopen this issue
