### ISSUE TITLE
[Bug] HA Autodiscovery detect router after reboot

### ISSUE THREAD

**Issue by 5a5cha** [Vaskivskyi/ha-asusrouter#741]
### The problem

After upgrading from version 0.24.2 to 0.26.0 and restarting HA the Autodiscover detects the router as new device.
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/21234719/f4586f88-c794-49d2-93b7-dff96dbd1bfe)

After wondering and maybe some update issues i deleted the existing configuration for the router and the AIMesh Node and set up all from scratch.

After the update last night from HA Core 2023.12.3 to HA Core 2023.12.4 the auto discover detects the router as new device again.
Did the configuration again and after successfully stored the settings the integration shows up as followed:
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/21234719/413b5d80-a35a-4e1b-b4bc-8d335748f8eb)
 

Edit 2:
After an additional restart of HomeAssistant the integration detects the router again as a new device :-)
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/21234719/77a52842-9f6c-4305-b989-216f67a401e9)

### Your device model

GT-AX11000

### Firmware type

Merlin

### Firmware version

3004.388.5

### Integration version with the issue

0.26.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.12.4

**Comment by Vaskivskyi** [comment]
Can you please turn on debug logging and reload the integration? At the beginning of the log, there will be several discovery messages from auto-discovery starting with:

```
Discovered SSDP device with serial number: 
Discovered SSDP device: 
```

Only the SN is checked to make sure the device is already configured once since this is the only value which should be unique (even though advanced users can change this value as well). There might be some issue either with this value or with the whole SSDP message.

In case the SN is the same as the one on your device and nothing happened to it, please, share the log messages to Yevhenii@Vaskivskyi.com. (You can also share them here, but they will contain IP addresses and serial number(s) of your device(s) which might be not something you'd like to do).

**Comment by Vaskivskyi** [comment]
Autodiscovery is removed in `0.29.0`, so the issue is closed now
