### ISSUE TITLE
[Feature] Connected Guest Devices Count

### ISSUE THREAD

**Issue by ankitduseja** [Vaskivskyi/ha-asusrouter#790]
### The problem

Is it possible to get a count of devices connected to the guest network only?

This can be used to monitor if visitors are at home or not.

### Specific device(s)?

No

### Firmware type

No

**Comment by Vaskivskyi** [comment]
This is not implemented directly yet, but can possibly be. How do you see this feature? As a sensor `connected_guest_5_1` numeric sensor? Or just total number of clients on all the guest networks?

I would need a proper context on the way you would like to use it, so that I can suggest the best solution. Maybe, it can already be done with the existing integration features, maybe something new should be implemented

**Comment by greteOne** [comment]
Hello
I‘m very interested in this feature too.
For me it would be perfect if I get the total number on clients on all guest networks.

**Comment by Morriz** [comment]
I am now trying the same with automation but it is impossible since you don't provide the correct event data when guest devices disconnect (`guest` flag is omitted). Can you at least make sure that `guest: true` is provided when a guest device disconnects? I presume you keep enough state to do so...

**Comment by Morriz** [comment]
of course it would be best if your solution provided the counter

**Comment by Morriz** [comment]
> I am now trying the same with automation but it is impossible since you don't provide the correct event data when guest devices disconnect (guest flag is omitted). Can you at least make sure that guest: true is provided when a guest device disconnects? I presume you keep enough state to do so...

I created a separate issue for that here: #843
