### ISSUE TITLE
asusr_connected_devices show not all Devices in Attributes

### ISSUE THREAD

**Issue by boheme61** [Vaskivskyi/ha-asusrouter#803]
### The problem

Hi Vaskivskyi
First a "fairly simple question.
I Have 1 entity in total count, i can't "locate" , Do the sensor count the Router as well, so tha't why i see 1 more ( In number, connected ) ?

To the "culprit "
Not all Devices are show in the Attributes List, of the sensor( clicking on the sensor, and view the attributes in UI ) ( i count no more than 23 devices, of i.e 29 in total(reported by the sensor)
Could this be doo to the extensive data, of the device_trackers ? , maybe it exceed a data-limit (somewhere) ?

in the DB, (shared_attrs) for Attributes " SELECT * FROM "state_attributes" where attributes_id = X ", it seems to be able to contain datas from more than i.e 27-29 devices (MAX_STATE_ATTRS_BYTES = 16384), so the limit doesn't seems to be in the TEXT data-type there. ?
( however it's not always it actually contain all devices there " depending upon which attributes_id you search on, ( Guess that depends upon the time i't updated ) , as some devices pops in and out regularly 

Maybe just a front-end limit ?
I Just wonder if this could be a cause that the asusr_connected_devices "count" keeps changing/ (not showing actual devices as online, spite they are)

BR

### Your device model

RT-AX68U

### Firmware type

Stock

### Firmware version

3.0.0.4.388_21732

### Integration version with the issue

Latest

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2024.2.4

**Comment by Vaskivskyi** [comment]
Hello,

1. The total number of connected devices should not include the router itself, as well as it should not include AiMesh nodes. It should reflect the same number as the Web UI on the AiMesh page (even if you use a single router)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/b7d1bdac-5a4d-45b5-98eb-b0cff40ceb6f)

2. I will try to check whether there might be any issues in the attributes due to the size limit in either DB or frontend. In the later case, I suppose, one should be able to see "more" in the dev. tools - templates.
3. But this in any case should not influence the number of the device (the value of the `connected_devices` sensor, since it's calculated from the backend library data before anything being written to the HA DB

**Comment by boheme61** [comment]
1. ok, maybe it's only sometimes i find there is 1 number more, than the Router Gui says
2. In Dev-Tools #States, there is listed .ie. a total of 28 (same as DB shows), when the count number also says 28
However, it's when you click the entity in the integration or in a View, and then click "attributes", it only show about 23, So it obviously seems like a HA "Front-end/UI" issue
3. As the States-Tool reflects the DB(array) and the shown Number, it seems like as above mentioned, Front-end/UI limitation

Thanks for your feedback
